[package]
name = "magba"
version = "0.1.0"
authors = ["Sira Pornsiriprasert <code@psira.me>"]

description = "Magnetic computation library for Rust"
categories = ["science", "simulation"]
keywords = ["magnet", "magnetic", "field", "analytical", "simulation"]
documentation = "https://docs.rs/magba"
homepage = "https://github.com/p-sira/magba"
repository = "https://github.com/p-sira/magba"
readme = "README.md"
license = "BSD-3-Clause"
edition = "2021"

[dependencies]
ellip = "0.1.2"
nalgebra = { version = "0.33.2" }
rayon = { version = "1.10.0", optional = true }

[dev-dependencies]
criterion = "0.5.1"
nalgebra = { version = "0.33.2", features = ["sparse"] }
nalgebra-sparse = { version = "0.10.0", features = ["io"] }
rayon = "1.10.0"

[features]
default = ["sources", "parallel"]
transform = []
sources = ["transform"]
parallel = ["dep:rayon", "nalgebra/rayon"]

[[bench]]
name = "bench"
harness = false
