name: Magba CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy
  test-default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test default
      run: cargo test
  test-no-default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test no-default
      run: cargo test --no-default-features
  test-sources:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test sources
      run: cargo test --no-default-features --features=sources
  test-parallel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - name: Test parallel
      run: cargo test --no-default-features --features=parallel