name: Magba CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install OpenBLAS
      run: sudo apt-get update; sudo apt-get install -y libopenblas-dev
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Run clippy
      run: cargo clippy 
    - name: Test default
      run: cargo test
    - name: Test no-default
      run: cargo test --no-default-features
    - name: Test sources
      run: cargo test --no-default-features --features=sources
    - name: Test parallel
      run: cargo test --no-default-features --features=parallel
    - name: Make docs
      run: cargo doc