name: Magba CI

permissions:
  contents: write

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy
  test-default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test default
      run: cargo test
  test-no-default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test no-default
      run: cargo test --no-default-features
  test-sources:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test sources
      run: cargo test --no-default-features --features=sources
  test-parallel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 
    - name: Test parallel
      run: cargo test --no-default-features --features=parallel
  test-unstable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test unstable
      run: cargo test --features=unstable
  test-nodefault-unstable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test unstable
      run: cargo test --no-default-features --features=unstable
  test-no-std:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test no_std
      run: cargo test --no-default-features --features=no_std
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Make doc
      run: cargo doc --no-deps
  format:
    runs-on: ubuntu-latest
    needs: [test-default, test-no-default, test-sources, test-parallel, test-unstable, test-nodefault-unstable, test-no-std]
    steps:
    - uses: actions/checkout@v4
    - name: Format codes
      run: |
        cargo fmt
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git diff --cached --quiet || (git commit -m "FMT: CI cargo fmt" && git push)