name: Magba CI

permissions:
  contents: write

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-
      - name: Clippy
        run: cargo clippy

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-24.04-arm]
        no_default: [false, true]
        features: ["", sources, parallel, unstable, no_std]
        exclude:
          # no_std always implies no-default-features
          - no_default: false
            features: no_std
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ matrix.os }}-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.no_default }}-${{ matrix.features }}
          restore-keys: |
            cargo-${{ matrix.os }}-${{ hashFiles('**/Cargo.lock') }}-
            cargo-${{ matrix.os }}-
      - name: Run tests
        shell: bash
        run: |
          FLAGS=""
          if [ "${{ matrix.no_default }}" = "true" ]; then
            FLAGS="$FLAGS --no-default-features"
          fi
          if [ -n "${{ matrix.features }}" ]; then
            FLAGS="$FLAGS --features=${{ matrix.features }}"
          fi
          cargo test $FLAGS
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-
      - name: Make doc
        run: cargo doc --no-deps
  format:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-
      - name: Format codes
        run: |
          cargo fmt
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git diff --cached --quiet || (git commit -m "FMT: CI cargo fmt" && git push)
